/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountInfoResponse {
    'frontier': string;
    'openBlock': string;
    'representativeBlock': string;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'balance': number;
    'modifiedTimestamp': string;
    'blockCount': string;
    'confirmationHeight': string;
    'accountVersion': string;
    'representative'?: string;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'weight'?: number;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'pending'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "frontier",
            "baseName": "frontier",
            "type": "string"
        },
        {
            "name": "openBlock",
            "baseName": "open_block",
            "type": "string"
        },
        {
            "name": "representativeBlock",
            "baseName": "representative_block",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "modifiedTimestamp",
            "baseName": "modified_timestamp",
            "type": "string"
        },
        {
            "name": "blockCount",
            "baseName": "block_count",
            "type": "string"
        },
        {
            "name": "confirmationHeight",
            "baseName": "confirmation_height",
            "type": "string"
        },
        {
            "name": "accountVersion",
            "baseName": "account_version",
            "type": "string"
        },
        {
            "name": "representative",
            "baseName": "representative",
            "type": "string"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AccountInfoResponse.attributeTypeMap;
    }
}

