/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PendingBlock } from './pendingBlock';

export class AccountsPendingResponse {
    'blocks': { [key: string]: { [key: string]: PendingBlock; }; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "{ [key: string]: { [key: string]: PendingBlock; }; }"
        }    ];

    static getAttributeTypeMap() {
        return AccountsPendingResponse.attributeTypeMap;
    }
}

