/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountsBalancesRequest {
    'action'?: AccountsBalancesRequest.ActionEnum;
    'accounts'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AccountsBalancesRequest.ActionEnum"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AccountsBalancesRequest.attributeTypeMap;
    }
}

export namespace AccountsBalancesRequest {
    export enum ActionEnum {
        AccountsBalances = <any> 'accounts_balances'
    }
}
