/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountsCreateRequest {
    'action'?: AccountsCreateRequest.ActionEnum;
    'wallet'?: string;
    'count'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AccountsCreateRequest.ActionEnum"
        },
        {
            "name": "wallet",
            "baseName": "wallet",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountsCreateRequest.attributeTypeMap;
    }
}

export namespace AccountsCreateRequest {
    export enum ActionEnum {
        AccountsCreate = <any> 'accounts_create'
    }
}
