/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountsPendingRequest {
    'action'?: AccountsPendingRequest.ActionEnum;
    'accounts'?: Array<string>;
    'count'?: string;
    'includeActive'?: boolean;
    'source'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AccountsPendingRequest.ActionEnum"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<string>"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string"
        },
        {
            "name": "includeActive",
            "baseName": "include_active",
            "type": "boolean"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AccountsPendingRequest.attributeTypeMap;
    }
}

export namespace AccountsPendingRequest {
    export enum ActionEnum {
        AccountsPending = <any> 'accounts_pending'
    }
}
