/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class AccountInfoRequest {
    'action'?: AccountInfoRequest.ActionEnum;
    'account'?: string;
    /**
    * Boolean, false by default. Returns representative when set to true. 
    */
    'representative'?: ModelBoolean;
    /**
    * Boolean, false by default. Returns weigth when set to true. 
    */
    'weight'?: ModelBoolean;
    /**
    * Boolean, false by default. Returns pending when set to true. 
    */
    'pending'?: ModelBoolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AccountInfoRequest.ActionEnum"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "representative",
            "baseName": "representative",
            "type": "ModelBoolean"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "ModelBoolean"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "ModelBoolean"
        }    ];

    static getAttributeTypeMap() {
        return AccountInfoRequest.attributeTypeMap;
    }
}

export namespace AccountInfoRequest {
    export enum ActionEnum {
        AccountInfo = <any> 'account_info'
    }
}
