/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActiveDifficultyResponse {
    'networkMinimum'?: string;
    'networkCurrent'?: string;
    'multiplier'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "networkMinimum",
            "baseName": "network_minimum",
            "type": "string"
        },
        {
            "name": "networkCurrent",
            "baseName": "network_current",
            "type": "string"
        },
        {
            "name": "multiplier",
            "baseName": "multiplier",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActiveDifficultyResponse.attributeTypeMap;
    }
}

