/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class ActiveDifficultyRequest {
    'action': ActiveDifficultyRequest.ActionEnum;
    /**
    * Boolean, false by default. Also returns the trend of difficulty seen on the network as a list of multipliers. Sampling occurs every 16 to 36 seconds. The list is ordered such that the first value is the most recent sample. 
    */
    'includeTrend'?: ModelBoolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ActiveDifficultyRequest.ActionEnum"
        },
        {
            "name": "includeTrend",
            "baseName": "include_trend",
            "type": "ModelBoolean"
        }    ];

    static getAttributeTypeMap() {
        return ActiveDifficultyRequest.attributeTypeMap;
    }
}

export namespace ActiveDifficultyRequest {
    export enum ActionEnum {
        ActiveDifficulty = <any> 'active_difficulty'
    }
}
