/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class BlockCreateRequest {
    'action'?: BlockCreateRequest.ActionEnum;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, `\"block\"` contains a JSON subtree instead of a JSON string.
    */
    'jsonBlock'?: ModelBoolean;
    'type'?: BlockCreateRequest.TypeEnum;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'balance'?: number;
    'key'?: string;
    'representative'?: string;
    'link'?: string;
    'work'?: string;
    'previous'?: string;
    'wallet'?: string;
    'account'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "BlockCreateRequest.ActionEnum"
        },
        {
            "name": "jsonBlock",
            "baseName": "json_block",
            "type": "ModelBoolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BlockCreateRequest.TypeEnum"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "representative",
            "baseName": "representative",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "work",
            "baseName": "work",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "wallet",
            "baseName": "wallet",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BlockCreateRequest.attributeTypeMap;
    }
}

export namespace BlockCreateRequest {
    export enum ActionEnum {
        BlockCreate = <any> 'block_create'
    }
    export enum TypeEnum {
        State = <any> 'state'
    }
}
