/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlockDataJson } from './blockDataJson';

export class BlockCreateResponse {
    'hash'?: string;
    'block'?: BlockDataJson;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "BlockDataJson"
        }    ];

    static getAttributeTypeMap() {
        return BlockCreateResponse.attributeTypeMap;
    }
}

