/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BlocksRequest {
    'action': BlocksRequest.ActionEnum;
    'hashes'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "BlocksRequest.ActionEnum"
        },
        {
            "name": "hashes",
            "baseName": "hashes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return BlocksRequest.attributeTypeMap;
    }
}

export namespace BlocksRequest {
    export enum ActionEnum {
        Blocks = <any> 'blocks'
    }
}
