/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BlockDataJson {
    'type'?: BlockDataJson.TypeEnum;
    'account'?: string;
    'previous'?: string;
    'representative'?: string;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'balance'?: number;
    'link'?: string;
    'linkAsAccount'?: string;
    'signature'?: string;
    'work'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BlockDataJson.TypeEnum"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "representative",
            "baseName": "representative",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "linkAsAccount",
            "baseName": "link_as_account",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "work",
            "baseName": "work",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BlockDataJson.attributeTypeMap;
    }
}

export namespace BlockDataJson {
    export enum TypeEnum {
        State = <any> 'state'
    }
}
