/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BlockCountRequest {
    'action': BlockCountRequest.ActionEnum;
    /**
    * _enable_control required, version 19.0+_ Default \"false\". If \"true\", \"cemented\" in the response will contain the number of cemented blocks. 
    */
    'includeCemented'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "BlockCountRequest.ActionEnum"
        },
        {
            "name": "includeCemented",
            "baseName": "include_cemented",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BlockCountRequest.attributeTypeMap;
    }
}

export namespace BlockCountRequest {
    export enum ActionEnum {
        BlockCount = <any> 'block_count'
    }
}
