/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BlockCountTypeResponse {
    'send': string;
    'receive': string;
    'open': string;
    'change': string;
    'stateV0': string;
    'stateV1': string;
    'state': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "send",
            "baseName": "send",
            "type": "string"
        },
        {
            "name": "receive",
            "baseName": "receive",
            "type": "string"
        },
        {
            "name": "open",
            "baseName": "open",
            "type": "string"
        },
        {
            "name": "change",
            "baseName": "change",
            "type": "string"
        },
        {
            "name": "stateV0",
            "baseName": "state_v0",
            "type": "string"
        },
        {
            "name": "stateV1",
            "baseName": "state_v1",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BlockCountTypeResponse.attributeTypeMap;
    }
}

