/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';
import { SubType } from './subType';

export class BlockInfo {
    'blockAccount'?: string;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'amount'?: number;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'balance'?: number;
    'height'?: string;
    'localTimestamp'?: string;
    'confirmed'?: ModelBoolean;
    'contents'?: string;
    'subtype'?: SubType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockAccount",
            "baseName": "block_account",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "localTimestamp",
            "baseName": "local_timestamp",
            "type": "string"
        },
        {
            "name": "confirmed",
            "baseName": "confirmed",
            "type": "ModelBoolean"
        },
        {
            "name": "contents",
            "baseName": "contents",
            "type": "string"
        },
        {
            "name": "subtype",
            "baseName": "subtype",
            "type": "SubType"
        }    ];

    static getAttributeTypeMap() {
        return BlockInfo.attributeTypeMap;
    }
}

