/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class BootstrapLazyRequest {
    'action': BootstrapLazyRequest.ActionEnum;
    'hash': string;
    /**
    * Boolean, false by default. Manually force closing of all current bootstraps. 
    */
    'force'?: ModelBoolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "BootstrapLazyRequest.ActionEnum"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "force",
            "baseName": "force",
            "type": "ModelBoolean"
        }    ];

    static getAttributeTypeMap() {
        return BootstrapLazyRequest.attributeTypeMap;
    }
}

export namespace BootstrapLazyRequest {
    export enum ActionEnum {
        BootstrapAny = <any> 'bootstrap_any'
    }
}
