/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class ChainRequest {
    'action': ChainRequest.ActionEnum;
    'block': string;
    'count': string;
    /**
    * _version 18.0+_  Number, 0 by default. Return the account chain block hashes offset by the specified number of blocks 
    */
    'offset'?: string;
    /**
    * _version 18.0+_  Boolean, false by default. Returns a list of block hashes in the account chain starting at block up to count (direction from open block up to frontier, from older blocks to newer). Equal to [successors](https://docs.nano.org/commands/rpc-protocol/#successors) 
    */
    'reverse'?: ModelBoolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ChainRequest.ActionEnum"
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "string"
        },
        {
            "name": "reverse",
            "baseName": "reverse",
            "type": "ModelBoolean"
        }    ];

    static getAttributeTypeMap() {
        return ChainRequest.attributeTypeMap;
    }
}

export namespace ChainRequest {
    export enum ActionEnum {
        Chain = <any> 'chain'
    }
}
