/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConfirmationInfo } from './confirmationInfo';

export class ConfirmationInfoResponse {
    'announcements'?: string;
    'lastWinner'?: string;
    /**
    * 1 raw is the smallest possible division and NANO/Nano (Mnano) is the current standard division used in most wallets, on exchanges, etc.
    */
    'totalTally'?: number;
    'blocks'?: { [key: string]: ConfirmationInfo; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "announcements",
            "baseName": "announcements",
            "type": "string"
        },
        {
            "name": "lastWinner",
            "baseName": "last_winner",
            "type": "string"
        },
        {
            "name": "totalTally",
            "baseName": "total_tally",
            "type": "number"
        },
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "{ [key: string]: ConfirmationInfo; }"
        }    ];

    static getAttributeTypeMap() {
        return ConfirmationInfoResponse.attributeTypeMap;
    }
}

