/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class ConfirmationInfoRequest {
    'action': ConfirmationInfoRequest.ActionEnum;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, `\"contents\"` contains a JSON subtree instead of a JSON string.
    */
    'jsonBlock'?: ModelBoolean;
    /**
    * Defaults to `\"true\"`. If `\"false\"`, disables contents for each block.
    */
    'contents'?: ModelBoolean;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, returns a list of votes representatives & its weights for each block.
    */
    'representatives'?: ModelBoolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ConfirmationInfoRequest.ActionEnum"
        },
        {
            "name": "jsonBlock",
            "baseName": "json_block",
            "type": "ModelBoolean"
        },
        {
            "name": "contents",
            "baseName": "contents",
            "type": "ModelBoolean"
        },
        {
            "name": "representatives",
            "baseName": "representatives",
            "type": "ModelBoolean"
        }    ];

    static getAttributeTypeMap() {
        return ConfirmationInfoRequest.attributeTypeMap;
    }
}

export namespace ConfirmationInfoRequest {
    export enum ActionEnum {
        ConfirmationInfo = <any> 'confirmation_info'
    }
}
