/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Confirmation } from './confirmation';
import { ConfirmationHistoryResponseConfirmationStats } from './confirmationHistoryResponseConfirmationStats';

export class ConfirmationHistoryResponse {
    'confirmationStats'?: ConfirmationHistoryResponseConfirmationStats;
    'confirmations'?: Array<Confirmation>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "confirmationStats",
            "baseName": "confirmation_stats",
            "type": "ConfirmationHistoryResponseConfirmationStats"
        },
        {
            "name": "confirmations",
            "baseName": "confirmations",
            "type": "Array<Confirmation>"
        }    ];

    static getAttributeTypeMap() {
        return ConfirmationHistoryResponse.attributeTypeMap;
    }
}

