/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConfirmationActiveRequest {
    'action': ConfirmationActiveRequest.ActionEnum;
    /**
    * Number, 0 by default. Returns only active elections with equal or higher announcements count. Useful to find long running elections 
    */
    'announcements'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ConfirmationActiveRequest.ActionEnum"
        },
        {
            "name": "announcements",
            "baseName": "announcements",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConfirmationActiveRequest.attributeTypeMap;
    }
}

export namespace ConfirmationActiveRequest {
    export enum ActionEnum {
        ConfirmationActive = <any> 'confirmation_active'
    }
}
