/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class KeyExpandResponse {
    '_private'?: string;
    '_public'?: string;
    'account'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_private",
            "baseName": "private",
            "type": "string"
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return KeyExpandResponse.attributeTypeMap;
    }
}

