/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelBoolean } from './modelBoolean';

export class PendingRequest {
    'action': PendingRequest.ActionEnum;
    'account': string;
    'count'?: number;
    /**
    * _version 19.0+_  Boolean, false by default. Additionally sorts the blocks by their amounts in descending order. 
    */
    'sorting'?: ModelBoolean;
    /**
    * _version 19.0+_  Boolean, false by default. Only returns block which have their confirmation height set or are undergoing confirmation height processing. 
    */
    'includeOnlyConfirmed'?: ModelBoolean;
    /**
    * _version 19.0+_  Boolean, false by default. Returns a list of pending block hashes with amount and source accounts 
    */
    'source'?: ModelBoolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "PendingRequest.ActionEnum"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "sorting",
            "baseName": "sorting",
            "type": "ModelBoolean"
        },
        {
            "name": "includeOnlyConfirmed",
            "baseName": "include_only_confirmed",
            "type": "ModelBoolean"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ModelBoolean"
        }    ];

    static getAttributeTypeMap() {
        return PendingRequest.attributeTypeMap;
    }
}

export namespace PendingRequest {
    export enum ActionEnum {
        Pending = <any> 'pending'
    }
}
