/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlockDataJson } from './blockDataJson';
import { ModelBoolean } from './modelBoolean';
import { SubType } from './subType';

export class ProcessRequest {
    'action': ProcessRequest.ActionEnum;
    /**
    * Defaults to `\"false\"`. If `\"true\"`, `\"block\"` contains a JSON subtree instead of a JSON string.
    */
    'jsonBlock'?: ModelBoolean;
    'block': BlockDataJson;
    'subtype'?: SubType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ProcessRequest.ActionEnum"
        },
        {
            "name": "jsonBlock",
            "baseName": "json_block",
            "type": "ModelBoolean"
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "BlockDataJson"
        },
        {
            "name": "subtype",
            "baseName": "subtype",
            "type": "SubType"
        }    ];

    static getAttributeTypeMap() {
        return ProcessRequest.attributeTypeMap;
    }
}

export namespace ProcessRequest {
    export enum ActionEnum {
        Process = <any> 'process'
    }
}
