/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * The version of the OpenAPI document: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkGenerateRequest {
    'action'?: WorkGenerateRequest.ActionEnum;
    'hash'?: string;
    'difficulty'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "WorkGenerateRequest.ActionEnum"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "difficulty",
            "baseName": "difficulty",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WorkGenerateRequest.attributeTypeMap;
    }
}

export namespace WorkGenerateRequest {
    export enum ActionEnum {
        WorkGenerate = <any> 'work_generate'
    }
}
