/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * OpenAPI spec version: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ActiveDifficultyResponse {
    'network_minimum'?: string;
    'network_current'?: string;
    'multiplier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "network_minimum",
            "baseName": "network_minimum",
            "type": "string",
            "format": ""
        },
        {
            "name": "network_current",
            "baseName": "network_current",
            "type": "string",
            "format": ""
        },
        {
            "name": "multiplier",
            "baseName": "multiplier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActiveDifficultyResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

