/**
 * nano-rpc-api
 * API specification for the [Nano Node RPC API](https://docs.nano.org/commands/rpc-protocol) 
 *
 * OpenAPI spec version: 19.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Confirmation } from './Confirmation';
import { ConfirmationHistoryResponseConfirmationStats } from './ConfirmationHistoryResponseConfirmationStats';
import { HttpFile } from '../http/http';

export class ConfirmationHistoryResponse {
    'confirmation_stats'?: ConfirmationHistoryResponseConfirmationStats;
    'confirmations'?: Array<Confirmation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "confirmation_stats",
            "baseName": "confirmation_stats",
            "type": "ConfirmationHistoryResponseConfirmationStats",
            "format": ""
        },
        {
            "name": "confirmations",
            "baseName": "confirmations",
            "type": "Array<Confirmation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConfirmationHistoryResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

